tasks:
  - init: |
      /workspace/rustlings/install.sh
      /workspace/.cargo/bin/rustup component add clippy
    command: /workspace/.cargo/bin/rustlings watch

vscode:
  extensions:
    - rust-lang.rust@0.7.8:CvNqMTgDdt3UXt+6BCDTVg==
